stages:
  - build

php:build:
  stage: build
  image: docker:stable
  services:
      - docker:dind
  script:
    - IMAGE_NAME_CURRENT=$CI_REGISTRY_IMAGE/ciis-php:$CI_COMMIT_REF_NAME
    - IMAGE_NAME_LATEST=$CI_REGISTRY_IMAGE/ciis-php:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_NAME_CURRENT -f Dockerfile .
    - docker push $IMAGE_NAME_CURRENT
    - echo "Commit tag set to $CI_COMMIT_TAG, tagging built image as latest."
    - docker tag $IMAGE_NAME_CURRENT $IMAGE_NAME_LATEST
    - docker push $IMAGE_NAME_LATEST
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^WIP/
      when: never
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web"'