name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        distro: ["debian-bullseye"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ matrix.distro }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            chrudosvorlicek/php-common:8.2-${{ matrix.distro }}
            chrudosvorlicek/php-common:8.2-${{ matrix.distro }}-${{ env.VERSION }}
